### ISSUE TITLE
Kubescape Playground not working as intended

### ISSUE THREAD

**Issue by suhasgumma** [saiyam1814/katacoda-scenarios#3]
* The script is only executing apt-install jq -y in kubescape playground.
* However, if I write a ".sh" file and execute it on the ubuntu environment it works as expected.

**Comment by suhasgumma** [comment]
* If I add "&&" at the end of each command in "foreground.sh", it works as expected in the killercoda playground.

* I should have tested the playground yesterday itself but didn't do so. Should I open a pull request after adding "&&" after each command @saiyam1814 ?

**Comment by suhasgumma** [comment]
@saiyam1814, Could you please take a look at this?

**Comment by saiyam1814** [comment]
Yes please open the PR for it

**Comment by suhasgumma** [comment]
#4
